book/urls.py
from django.urls import path
from book import views

app_name = 'book'
urlpatterns = [
    # 書籍
    path('', views.book_list, name='book_list'),  # 一覧
    path('search/', views.book_search, name='book_search'),
    path('add/', views.book_edit, name='book_add'),  # 登録
    path('mod/<int:book_id>/', views.book_edit, name='book_mod'),  # 修正
    path('del/<int:book_id>/', views.book_del, name='book_del'),   # 削除
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('book.urls')),
    #path('admin/', admin.site.urls),
]

book/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    """書籍"""
    name = models.CharField('書籍名', max_length=255)
    author = models.CharField('作者', max_length=255)
    publisher = models.CharField('レーベル', max_length=255, blank=True)
    number = models.IntegerField('巻数', blank=True, default=0)

    def __str__(self):
        return self.name


class Impression(models.Model):
    """感想"""
    book = models.ForeignKey(
        Book,
        verbose_name='書籍',
        related_name='impressions',
        on_delete=models.CASCADE)
    comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment

book/forms.py
from django.forms import ModelForm, Form, IntegerField, CharField
from book.models import Book


class BookForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Book
        fields = ('name', 'author', 'publisher', 'number',)


class SearchForm(Form):
    """書籍サーチのフォーム"""
    name = CharField(label = '作品名', required=False)
    author = CharField(label = '作者', required=False)
    publisher = CharField(label = 'レーベル', required = False)

    min_number = IntegerField(label='最小巻数', required=False)
    max_number = IntegerField(label='最大巻数', required=False)

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from book.models import Book
from book.forms import BookForm, SearchForm


def book_list(request):
    """書籍の一覧"""
    # return HttpResponse('書籍の一覧')
    books = Book.objects.all().order_by('number')
    return render(request,
                  'book/book_list.html',     # 使用するテンプレート
                  {'books': books})         # テンプレートに渡すデータ


def book_edit(request, book_id=None):
    """書籍の編集"""
    # return HttpResponse('書籍の編集')
    if book_id:   # book_id が指定されている (修正時)
        book = get_object_or_404(Book, pk=book_id)
    else:         # book_id が指定されていない (追加時)
        book = Book()

    if request.method == 'POST':
        # POST された request データからフォームを作成
        form = BookForm(request.POST, instance=book)
        if form.is_valid():    # フォームのバリデーション
            book = form.save(commit=False)
            book.save()
            return redirect('book:book_list')
    else:  # GET の時
        form = BookForm(instance=book)  # book インスタンスからフォームを作成

    return render(
        request,
        'book/book_edit.html',
        dict(form=form, book_id=book_id))


def book_del(request, book_id):
    """書籍の削除"""
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('book:book_list')


def book_search(request):
    """書籍の検索"""
    if request.method == 'POST':
        # POST された request データからフォームを作成
        form = SearchForm(request.POST)
        if form.is_valid():    # フォームのバリデーション

            min_number = request.POST['min_number']
            max_number = request.POST['max_number']
            name_req = request.POST['name']
            author_req = request.POST['author']
            publisher_req = request.POST['publisher']

            if request.POST['min_number'] == '':
                min_number = '0'
            if request.POST['max_number'] == '':
                max_number = '500'

            books = Book.objects.filter(
                name__icontains=name_req,
                author__icontains=author_req,
                publisher__icontains=publisher_req,
                number__gte=min_number,
                number__lte=max_number).order_by("number")

            return render(request,
                          'book/book_search_result.html',     # 使用するテンプレート
                          {'books': books})
    else:    # GET の時
        form = SearchForm(request.GET)  # book インスタンスからフォームを作成
    return render(request, 'book/book_search.html', dict(form=form))

book/templates/book/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-    <link rel="stylesheet" type="text/css"  href="./static/book/css/bootstrap.min.css"> 
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}My books{% endblock %}</title>
</head>

<body>
    <div class="container">
        {% block content %}
        {{ content }}
        {% endblock %}
    </div>
    <script src="{% static 'book/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'book/js/bootstrap.bundle.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

book/templates/book/book_edit.html
{% extends "book/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
{% if book_id %}
<form action="{% url 'book:book_mod' book_id=book_id %}" method="post">
    {% else %}
    <form action="{% url 'book:book_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="submit" class="btn btn-primary">送信</button>
            </div>
        </div>
    </form>
    <a href="{% url 'book:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
    {% endblock content %}

book/templates/book/book_edit_simple.html
{% extends "book/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
{% if book_id %}
<form action="{% url 'book:book_mod' book_id=book_id %}" method="post">
    {% else %}
    <form action="{% url 'book:book_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="submit" class="btn btn-primary">送信</button>
            </div>
        </div>
    </form>
    <a href="{% url 'book:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
    {% endblock content %}

book/templates/book/book_list.html
{% extends "book/base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">書籍の一覧</h4>
<a href="{% url 'book:book_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<a href="{% url 'book:book_search' %}" class="btn btn-primary btn-sm my-3">検索</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">書籍名</th>
            <th scope="col">作者</th>
            <th scope="col">レーベル</th>
            <th scope="col">巻数</th>
            <th scope="col">操作</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <th scope="row">{{ book.name }}</th>
            <td>{{ book.author }}</td>
            <td>{{ book.publisher }}</td>
            <td>{{ book.number }}</td>
            <td>
                <a href="{% url 'book:book_mod' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
                <a href="{% url 'book:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

book/templates/book/book_search.html
{% extends "book/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の検索{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">書籍の検索</h4>
<form action="{% url 'book:book_search' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
        <div class="offset-md-3 col-md-9">
            <button type="submit" class="btn btn-primary">送信</button>
        </div>
    </div>
</form>
<a href="{% url 'book:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

book/templates/book/book_search_result.html
{% extends "book/base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">書籍の検索結果</h4>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">書籍名</th>
            <th scope="col">作者</th>
            <th scope="col">レーベル</th>
            <th scope="col">巻数</th>
            <th scope="col">操作</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <th scope="row">{{ book.name }}</th>
            <td>{{ book.author }}</td>
            <td>{{ book.publisher }}</td>
            <td>{{ book.number }}</td>
            <td>
                <a href="{% url 'book:book_mod' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
                <a href="{% url 'book:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'book:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}